;; configure org mode
(setq org-directory "~/org")
(setq org-default-notes-file "~/org/notes/refile.org")
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
(setq org-hide-leading-stars t)
(setq org-log-done 'time)
(setq org-log-done 'note)
